### ISSUE TITLE
Safety liability data into target Profile

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#102]
Safety liability data from http://www.nature.com/nrd/journal/v11/n12/full/nrd3845.html into target Profile

**Comment by ElaineMcA** [comment]
@gkos-bio  - do you already have some additional info on how this could be accomplished to increase annotation here?

**Comment by ElaineMcA** [comment]
Closing as @EPetsalaki and @MichaelaEBI will address as part of committee working on Safety data inclusion in OT.
