### ISSUE TITLE
include basic data about pharmability/druggability for each target

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#11]
There has been some feedback that druggability should not play a role in the score, but only _decorate_ each gene with the information. The rationale is that new modalities could allow to target previously unaccessible genes and if the biology behind them is strongly indicative, poor druggability should not be seen as an insurmountable challenge.

Potential sources:
https://www.biostars.org/p/17392/#17396
http://dgidb.genome.wustl.edu/ - search for drug-gene interactions by gene or drug names 
https://www.drugbank.ca/
https://www.ebi.ac.uk/chembl/drugebility/structure is a structure-based druggablity search engine. Users can survey different types of druggability scores of a given protein structure

https://www.ebi.ac.uk/chembl/api/data/binding_site
http://www.cbs.dtu.dk/services/SignalP/

**Comment by andrewhercules** [comment]
Issue closed as the integration of the tractability data pipeline output into the Open Targets Platform will address this for small molecule and antibody modalities - with further modalities planned for subsequent releases.

See [platform repo - add drug entity project](https://github.com/opentargets/platform/projects/1) for more information.
