### ISSUE TITLE
enrich in batch search based on pathways not in reactome

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#110]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  

Private deployments of the platform usually leverage other pathway resources. 
It would be useful for the enrichment analysis to leverage that data as well.

* [ ] **HOW are we going to solve the problem?**  

Perhaps we could make gene sets or pathway as a separate entity.

* [ ] **WHAT would this look like?**

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #380](https://github.com/opentargets/platform/issues/380) via [**ZenHub**](https://www.zenhub.com/)
