### ISSUE TITLE
Find drugs that could be repurposed using the current disease-disease viewer

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#111]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  

We showcase disease-disease similarity, but there is no evident information on whether there are any drugs in common.

* [ ] **HOW are we going to solve the problem?**  

Add a filter for those targets that *do* have a compound/drug against them, in either one of the disease

![image](https://user-images.githubusercontent.com/112610/34488952-5eb62d1c-efd2-11e7-9dbb-662b14266bfe.png)

* [ ] **WHAT would this look like?**

Alternatively, go to a drug profile page and have a "suggestion" section that links based on eg. "drug similarity" , "similar baseline expression"..

**Comment by ElaineMcA** [comment]
1. Location in platform would be on disease profile page - current feature, enhancement filter there.

2. Data sought needed is already here: https://www.targetvalidation.org/summary?drug=CHEMBL7413

"Similar baseline expression" - need to clarify request here.
