### ISSUE TITLE
Create Drug entity to be modular and extensible

### ISSUE THREAD

**Issue by mkarmona** [opentargets/roadmap#113]
## Description
* [ ] **WHY - What is the problem this feature would answer?** 
Improved drug coverage in OT Platform (DrugBank/PubChem, drug combinations, non-protein targets)

* [ ] **HOW are we going to solve the problem?**  

Build drug/compound index
Backend/ API work related to search and drug summary calls
Frontend UX changes required to reflect updated drug summary page and drug tables.

**Comment by deniseOme** [comment]
As per the "drug entity to-be" and the improvements on the drug page it may be worth considering (perhaps it has been?!?!?) adding PubChem IDs as xrefs.

There are users out there who want to map PubChem IDs to target IDs (e.g. UniProt IDs or names) e.g. https://www.biostars.org/p/328587/

ChEMBL has the information when the mapping between the two resources is available: e.g. ChEMBL1000 and PubChem 2678.

**Comment by ckongEbi** [comment]
- Compound index :
            Implemented in branch `ck_compound` , run with option `--cpd`
           `https://github.com/opentargets/data_pipeline/tree/ck_compound`
- A sample compound index created with 15k compounds on DEV machine:

```sh
    ckong-ml:data_pipeline ckong$ curl http://localhost:9200/_cat/indices/ck_cpd3*
    yellow open ck_cpd3_compound-data OPFt1R6UQOGq0dzGKQx4PA 5 1 15000 0 29.8mb 29.8mb
```
- Still to do:
     parallelize the run to improve speed of importing 1.8 mil ChEMBL compounds (regardless of indication & mechanism data availability)
     (@mkarmona  is aware and has been helping)

**Comment by ckongEbi** [comment]
@MichaelaEBI

**Comment by ElaineMcA** [comment]
Rescheduled per prioritisation discussions and roadmap update Dec2018.

**Comment by ElaineMcA** [comment]
Moved and epic created in platform repo here: https://github.com/opentargets/platform/issues/451
