### ISSUE TITLE
Review and streamline existing ontology code in preparation for advent of EFO 3 and MONDO

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#114]
@elipapa commented on [Fri Sep 15 2017](https://github.com/opentargets/platform_semantic/issues/9)

## Description
* [ ] **WHY - What is the problem this feature would answer?**  
Multiple ontologies are referenced by Open Targets (e.g. EFO, HPO, MP) to assure consistent mapping across different data sources.
As part of maintenance plans, the intention is to review both current process and code to simplify and separate from the main data pipeline code as well as resolve any open maintenance tickets and improve mapping and coverage.

* [ ] **HOW are we going to solve the problem?**  
Step 1:  
Separate ontology code from data pipeline code, assuring QC checks versus existing code in use are in place and extended.

Step 2: 
Review phenotype categories - in order to enable a common highest level categorisation to be used to map across all of the ontologies.

Updates for disease profile page and target profile pages need to be scoped as appropriate.

Future step:
Consider extending Disease profile page to include similar phenotypes (in addition to similar diseases).

**Comment by ElaineMcA** [comment]
@elipapa  or @gkos-bio: Can either of you please explain/ expand what would be required to achieve this and what value this would bring in more detail - to help with prioritisation.

Not sure if this is something that will be superseded by Mondo or could be worked upon with other Ontology maintenance tickets cited.

Many thanks.

Elaine

**Comment by afaulconbridge** [comment]
I can expand this once I'm back from holiday, if it's not already done by then.

**Comment by ElaineMcA** [comment]
Closing and moving epic to platform repository: https://github.com/opentargets/platform/issues/446
