### ISSUE TITLE
no phenotypes for motor neuron disease

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#116]
@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_semantic/issues/6)

@elipapa commented on [Mon Feb 20 2017](https://github.com/opentargets/platform_issues_triage/issues/3)

@nikiforosk commented on [Mon Feb 13 2017](https://github.com/opentargets/features/issues/68)

While talking to Shila from Biogen last Friday, I noticed that we don't have any phenotypes for motor neuron disease:
https://www.targetvalidation.org/disease/EFO_0003782

@gkos-bio Is that correct? See e.g. http://www.mndcare.net.au/Overview/Motor-neurone-disease/Phenotypes.aspx 

cc/ @opentargets/efo_mapping

**Comment by ElaineMcA** [comment]
Need to identify a new source of phenotypes in disease profile - HPO service no longer exists.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #91](https://github.com/opentargets/platform/issues/91) via [**ZenHub**](https://www.zenhub.com/)
