### ISSUE TITLE
Missing disease description or truncated

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#119]
@gkos-bio commented on [Fri Mar 17 2017](https://github.com/opentargets/platform_semantic/issues/3)

could be a processing issue in the data pipeline or something went wrong when EFO was released.

---

@gkos-bio commented on [Fri Mar 17 2017](https://github.com/opentargets/platform_semantic/issues/3#issuecomment-287338828)

PTEN hamartoma tumor syndrome: description is truncated in ORDO

---

@gkos-bio commented on [Fri Mar 17 2017](https://github.com/opentargets/platform_semantic/issues/3#issuecomment-287339579)

Cowden syndrome: the definition from Orphanet is truncated. 
The definition from DO is better:
An autosomal dominant disease characterized by multiple noncancerous, tumor-like growths (hamartomas) and an increased risk of certain forms of cancer, especially breast, thyroid and endometrium. It is caused by mutations in the PTEN, SDHB, SDHD and KLLN genes. [ url:http://rarediseases.info.nih.gov/gard/6202/cowden-syndrome/resources/1 url:http://en.wikipedia.org/wiki/Cowden_syndrome url:http://ghr.nlm.nih.gov/condition/cowden-syndrome ]

**Comment by ElaineMcA** [comment]
@gkos-bio to submit ticket to EFO.

@gkos-bio to write query for inclusion in data pipeline QC to bridge any gaps within OT.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #87](https://github.com/opentargets/platform/issues/87) via [**ZenHub**](https://www.zenhub.com/)
