### ISSUE TITLE
search by SNP on the main platform

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#12]
input a SNP, get a (list?) of targets

extending batch search (which is being developed in opentargets/rest_api#14 and https://github.com/opentargets/webapp/tree/batch-search) to SNPs would also be desirable. 

_alternatively_ open a fully featured 'SNP page' that gives information about the SNP => gene link

showcasing to some extent where the mapping comes from (eg. LD, gene region, eQTL) will be useful, especially if we are relying on postgap by now.

**Comment by ElaineMcA** [comment]
Review after feedback from Genetics portal Oct/ Nov 2018 to firm up precise requirements.

**Comment by ElaineMcA** [comment]
Further planning pending review and feedback from ASHG meeting in Oct2018.

**Comment by ElaineMcA** [comment]
Closing post ASHG and Integration day feedback review with Genetics team.
