### ISSUE TITLE
missing literature evidence due to EFO synonyms not covering roman numerals

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#120]
@ckongEbi commented on [Mon Mar 06 2017](https://github.com/opentargets/platform_semantic/issues/2)

Can we add Mucolipidosis type IV as a synonym for Mucolipidosis type 4. 

In addition do we know if EFO have roman numeral covered in all the synonyms?

On 06/03/2017 17:12, Şenay Kafkas wrote:
> Hi,
>
> Our dictionary based tool is aware of
> -greek letters and symbols
> -plural singular forms
> -lower case/ upper case of the first character of a given term
>
> only. If you realise any synonyms that our tool cannot detect, you can directly contact Sira and make a request to add it to EFO. Once it is added to the EFO, our tool will be able to annotate it.
>
> Thanks
> Senay
>
> On 06/03/17 17:05, Chuang Kee Ong wrote:
>>
>>

---

@iandunham commented on [Tue Mar 07 2017](https://github.com/opentargets/platform_semantic/issues/2#issuecomment-284684231)

WE might want to look more widely at whether Roman numerals are used in many disease synonyms.

---

@nikiforosk commented on [Tue Mar 07 2017](https://github.com/opentargets/platform_semantic/issues/2#issuecomment-284699651)

They are used for some targets too, e.g. Claire once wrote TGFBRII instead of TGFBR2: 
https://www.targetvalidation.org/target/ENSG00000163513

By the way, searching for TGFBRII gives an ooops: 
https://www.targetvalidation.org/search?src=q:TGFBRII

**Comment by ElaineMcA** [comment]
EuropePMC  - not implemented for moment.
