### ISSUE TITLE
antagonist versus inhibitor: drug activities

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#122]
@deniseOme commented on [Thu Jan 04 2018](https://github.com/opentargets/platform_issues/issues/44)

The terms under activity (e.g. antagonist) in a page like this:

https://www.targetvalidation.org/evidence/ENSG00000180210/HP_0004419?view=sec:known_drug

come from ChEMBL in our evidence strings.

We should chat again to ChEMBL about what the right terms should be (antagonist? inhibitor?), and whether or not we are receiving them.

The choice of 'antagonist' may derive from an old discussion between Chembl and ourselves (maybe Sam originally). 

This may be a semantic issue discussed elsewhere (https://www.researchgate.net/post/What_is_the_difference_between_an_antagonist_and_an_inhibitor) but we need to find out if inhibitor is used for enzymes, antagonist for receptors.

w/ @ckongEbi @apierleoni @iandunham @MichaelaEBI

---

@deniseOme commented on [Fri Jan 05 2018](https://github.com/opentargets/platform_issues/issues/44#issuecomment-355531912)

@gkos-bio uses the following for other drug data in the GSK version
- agonist, 
- antagonist, 
- modulator (e.g. for receptors), 
- inhibitor, 
- blocker (e.g. calcium channel), 
- chelator (chelating agents), 
- opener (e.g. potassium channel) and
- others.

The links provided by @gkos-bio (below) can be used during the discussion with ChEMBl.

https://www.tocris.com/resources/pharmacological-glossary
https://www.unboundmedicine.com/washingtonmanual/index/Davis-Drug-Guide/Pharmacological_Index

Besides, we may need to revisit whether the activity reported (e.g. antagonist) should refer to the target (as it stands) or the MOA of the drug.

**Comment by andrewhercules** [comment]
Issue closed as semantic name issues should be discussed with ChEMBL. Perhaps @MichaelaEBI, this can be part of discussions for the drug entity?
