### ISSUE TITLE
add compounds/drugs on pre-clinical stage

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#126]
@deniseOme commented on [Mon Oct 23 2017](https://github.com/opentargets/platform_issues/issues/40)

This is one compound ARUK Oxford DDI where interested in:

https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1957266

We've got it here:
http://www.targetvalidation.org/summary?drug=CHEMBL1957266

More info on this compound (including mechanism of action):
http://www.chemicalprobes.org/jq1
https://www.ncbi.nlm.nih.gov/pubmed/20871596

They would like to see this compound listed under drugs for this target:

http://www.targetvalidation.org/target/ENSG00000239713

There is some target information from chemical probes under target details:

<img width="543" alt="screen shot 2017-10-23 at 18 06 13" src="https://user-images.githubusercontent.com/6472381/31902450-d1cf2706-b81c-11e7-9bc5-ec495f7ee5b1.png">

---

@iandunham commented on [Tue Oct 24 2017](https://github.com/opentargets/platform_issues/issues/40#issuecomment-338930763)

I can't see APOBEC3G amongst the list of targets that ChEMBL curates at https://www.ebi.ac.uk/chembl/target/results/keyword for this drug, and the chemical probes site just gives the BRD set of proteins. Where does the information that APOBEC3G is a target for this come from? i.e. how would we get the information, other than someone telling us?

---

@deniseOme commented on [Tue Oct 24 2017](https://github.com/opentargets/platform_issues/issues/40#issuecomment-338932301)

This is what I found:
https://www.ebi.ac.uk/chembl/target/inspect/CHEMBL1741217

Would this suffice?

---

@iandunham commented on [Tue Oct 24 2017](https://github.com/opentargets/platform_issues/issues/40#issuecomment-338933581)

Is APOBEC3G in the list of compounds found in that page (there are a lot)? The request seemed to be about adding the compound under the APOBEC3G drugs but is it actually a target or just has some activity towards that target?

---

@deniseOme commented on [Tue Oct 24 2017](https://github.com/opentargets/platform_issues/issues/40#issuecomment-338947686)

As far I understood, it had some activity towards the target and this is known in the pre-clinical stage.

They want to get compounds targeting a protein, not only drugs, not only drugs already marketed or approved for clinical trials.

**Comment by andrewhercules** [comment]
Issue triage notes:

- Platform now includes chemical probes information from the Structural Genomics Consortium, the Chemical Probes Portal, Open Science Probes, and ProbeMiner
- Example given - [CHEMBL1957266](http://www.targetvalidation.org/summary?drug=CHEMBL1957266) - appears in the Platform as JQ1, which can be found on the [BRD2 target profile page](https://www.targetvalidation.org/target/ENSG00000204256) in the Chemical Probes section
- Introduction of drug entity will also increase coverage of drugs/compounds in pre-clinical stage

**Comment by andrewhercules** [comment]
Issue closed as per triage notes above
