### ISSUE TITLE
Brain RNAseq and BrainMap

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#129]
@deniseOme commented on [Fri Jul 21 2017](https://github.com/opentargets/platform_issues/issues/34)

https://web.stanford.edu/group/barres_lab/brain_rnaseq.html

http://www.brain-map.org/

**Comment by elipapa** [comment]
from aruk workshop

**Comment by MichaelaEBI** [comment]
BrainMap is the Allen Brain Atlas. Both resources are logged in the '[Data Source Backlog](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1874651347)' on Google Drive in the 'Expression Data Sources' tab and will be assessed by Laura Huerta Martinez.
