### ISSUE TITLE
Include the target symbol on the drugs section

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#130]
@deniseOme commented on [Fri May 12 2017](https://github.com/opentargets/platform_issues/issues/33)

Include the target symbol on the drugs section of the target profile page (this had been asked in Heidelberg as well) e.g.

https://www.targetvalidation.org/evidence/ENSG00000114013/EFO_0001421?view=sec:known_drugs

The users can go to ChEMBL and get that information as it stands but we may want to revisit the table time permitting...

**Comment by andrewhercules** [comment]
Issue closed as data table within Drugs section on target/disease profile pages and evidence pages contains the target symbol for each evidence string. See below for an example:

![screen shot 2018-08-09 at 17 13 44](https://user-images.githubusercontent.com/7490258/43911525-9e191efc-9bf7-11e8-8e3e-8bf244b807c5.png)
