### ISSUE TITLE
Replacing 'Genetic Associations' by 'Genetic Evidence'?

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#132]
@MayaGhoussaini commented on [Tue May 09 2017](https://github.com/opentargets/platform_issues/issues/30)

@iandunham @elipapa @gkos-bio @emepyc @apierleoni 

Do you think it is possible to replace ‘Genetic Associations’ on the platform by ‘Genetic Evidence’ or something along those lines? I find that ‘Genetic associations’ can be confused with associations found through GWAS while the platform provides genetic links for both Common and Mendelian diseases. 

---

@iandunham commented on [Tue May 09 2017](https://github.com/opentargets/platform_issues/issues/30#issuecomment-300099038)

Definitely worth considering.  Although we could just go for "Genetics" as none of the other data types use the word association or evidence. Before doing anything, discuss with Niki to see what the background on how we got to associations is.

---

@MayaGhoussaini commented on [Tue May 09 2017](https://github.com/opentargets/platform_issues/issues/30#issuecomment-300100788)

Sure. Thank you!

**Comment by elipapa** [comment]
@andrewhercules do you think we can make a decision and close this? ;)

**Comment by andrewhercules** [comment]
@elipapa I would recommend that we change it to "Genetic Evidence" - it makes sense given that the user would be on a page expecting evidence supporting the link between a specific disease and a specific target.

As a side note, I've added a point to review how we name accordion sections to my design pattern library project - it'll remind me to revisit and talk with users about how we label all of the other sections on the page.

@peatroot and @LucaFumis - could we please include this change in the webapp? Thank you! :-)

**Comment by MayaGhoussaini** [comment]
I personally think that this would make more sense and will avoid users’ confusion.

Maya

--
Maya Ghoussaini, PhD
Genetic Analysis Team Leader
Open Targets, Wellcome Trust Sanger Institute
Hinxton, Cambridge CB10 1SD, UK
Tel: +44 (0) 1223494378
Email: mg29@sanger.ac.uk<mailto:hf6@sanger.ac.uk>

**Comment by andrewhercules** [comment]
Issue closed - deemed to be low priority and will be resolved with an eventual re-write and re-design of the Platform layout.
