### ISSUE TITLE
Alzheimer's with apostrophe (instead of Alzheimers without apostrophe)

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#133]
@nikiforosk commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29)

We spell "Alzheimers" without a apostrophe in the UI, e.g. in the associations page:
https://www.targetvalidation.org/disease/EFO_0000249/associations

![ad-associations-1493546001879](https://cloud.githubusercontent.com/assets/20280139/25563696/752a5d44-2d99-11e7-8841-b5667d402f30.png)

But if you search for "Alzheimers" on the web, google will correct it to "Alzheimer's" with apostrophe:
![screen shot 2017-04-30 at 11 33 35](https://cloud.githubusercontent.com/assets/20280139/25563698/a26c8d36-2d99-11e7-9016-3cbd62a0c62c.png)

Alzheimer's Research UK and other charities related to the disease also seem to use the apostrophe:
https://www.alzheimers.org.uk/info/20007/types_of_dementia/2/alzheimers_disease

It is named after Alois Alzheimer so it makes sense to have an apostrophe:
https://en.wikipedia.org/wiki/Alzheimer%27s_disease#History

I think that @deniseOme mentioned this in the past but I couldn't find an issue in github.

Notice that we spell Parkinson's disease with an apostrophe (as expected):
https://www.targetvalidation.org/disease/EFO_0002508

---

@nikiforosk commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298224808)

I want to use Alzheimer's in the example workflow of the UX paper so it will be helpful if this is prioritised. 

---

@emepyc commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298226426)

This is data related. The UI just displays whatever disease name it receives from the API.
(btw, you probably mean _apostrophe_ instead of _hyphen_)

---

@nikiforosk commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298226786)

Yes it's apostrophe, thanks. Who can correct this in the data?

---

@emepyc commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298227127)

It is possible that this has to be changed in the EFO itself? (ie the SPOT team). In any case I suppose you should ping @gkos-bio or @ckongEbi.

---

@deniseOme commented on [Sun Apr 30 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298241352)

Alzheimers is one of the names of the disease as well as Alzheimer's, Alzheimers dementia  and Alzheimer in EFO and DO (disease ontology):

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000249

Synomym as well in Disease Ontology:
http://disease-ontology.org/

![screen shot 2017-04-30 at 17 09 01](https://cloud.githubusercontent.com/assets/6472381/25565865/cb04c37a-2dc7-11e7-8f19-66a11df2670a.png)

It's important to allow as many synonyms as possible to be matched to a given search term for both the user and for the text mining, as there may be authors using Alzheimers instead of Alzheimer's in their scientific papers.

Even in this clinical trial record, there is mention to Alzheimers without the apostrophe (check under Official Title):

https://clinicaltrials.gov/ct/show/NCT00498602

If you want the name in the Platform to be with an apostrophe, you may want to create a ticket with SPOT (Functional genomics, JIRA).

---

@ckongEbi commented on [Mon May 01 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298359038)

@nikiforosk @emepyc When it comes to EFO related issue 

Submit a ticket directly to EFO team as suggested by Denise, e.g.
https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1391

Or create a wiki issue here, @gkos-bio will collate them and submit to Sira. 
https://github.com/opentargets/platform_semantic

---

@nikiforosk commented on [Tue May 02 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-298612082)

@gkos-bio I've submitted a ticket to the EFO:
https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1396

Hopefully they'll fix it before we submit the paper (somehow I'm not that confident about this)...

@deniseOme I think it's OK to have "Alzheimers" as a synonym and I understand why you'll find it like that in papers and clinical trials. But the official name in the ontology should have an apostrophe.

---

@nikiforosk commented on [Tue May 16 2017](https://github.com/opentargets/platform_issues/issues/29#issuecomment-301776811)

Sira fixed this in the EFO. Below is some action for @gkos-bio (from Sira's email):

the issue has been resolved on the EFO side. The ticket has been closed with the comment that Alzheimer’s disease (with the apostrophe) is now set to be the preferred label. The rdfs:label remains without apostrophe for backward compatibility with the older OWL editor on the other users’ ends. I have discussed this with Gautier that OpenTargets should first look at the preferred labels in EFO. When preferred_label is not available for a class, then use rdfs:label.

**Comment by gkos-bio** [comment]
This is actually not fixed at all.
https://github.com/EBISPOT/efo/issues/193

**Comment by andrewhercules** [comment]
Triage notes:

- Corresponding issue raised in [EBISPOT's EFO repo (#193)](https://github.com/EBISPOT/efo/issues/193) has been marked closed as of 2 July 2018
- @deniseOme, @MichaelaEBI, and @ElaineMcA, can we please add this to the data QC for the 18.08 release? If it appears as it should, then this issue can be closed

**Comment by ElaineMcA** [comment]
https://qa.targetvalidation.org/disease/EFO_0000249/associations

checked for 18.08.

Resolved.

![screen shot 2018-08-23 at 13 10 59](https://user-images.githubusercontent.com/40168275/44524622-2f34c600-a6d6-11e8-915a-fd756e6679e5.png)
