### ISSUE TITLE
mouse strains SNPs and the data for the Sanger Knockout project

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#137]
@elipapa commented on [Tue Feb 21 2017](https://github.com/opentargets/platform_issues/issues/10)

> I'd like to see the Sanger database on polymorphisms in different inbred mouse strains. It might be good when looking for tools to investigate a certain gene. The Sanger Mouse Genome Project also has a data base with all the data from their various knock out mice with information about all aspects of physiology (neurology tests, blood cell count, infection resistance) that might be useful if incorporated.

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues/issues/10#issuecomment-296715451)

need to compare to http://www.mousephenotype.org/ as a data source

**Comment by ElaineMcA** [comment]
Assess if this makes sense and the level of effort involved.  Could be located on target profile page similar to Chemical probes.

**Comment by MichaelaEBI** [comment]
@gkos-bio, is this ticket still relevant? What is the 'Sanger DB on polymorphisms in different inbred mouse strains'?

**Comment by ElaineMcA** [comment]
Closing as any agreed actions will be addressed as appropriate within platform repository roadmap epics.
