### ISSUE TITLE
Unify style with a pattern library

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#139]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  

Inconsistencies between different products and having to reinvent the CSS/HTML/UX wheel every time.

* [ ] **HOW are we going to solve the problem?**  

Building a pattern library with elements that have been UX tested.

* [ ] **WHAT would this look like?**

**Comment by andrewhercules** [comment]
Issue closed as style guide is being developed for Genetics Portal (based on Material UI) and for existing webapp, many common elements have been standardised. Will review and revisit this issue with a re-write and re-design of the Platform UI.
