### ISSUE TITLE
exposing odds ratio and other stats for GWAS data on the web app

### ISSUE THREAD

**Issue by deniseOme** [opentargets/roadmap#141]
Users at Takeda and previously in Biogen (https://github.com/opentargets/platform_issues/issues/6) say odds ratio (OR), beta coefficient, confidence interval should be exposed on the UI.

**What is the problem this feature would answer?**
P value does not take into account sample size and may no longer be informative in determining an association (https://www.nature.com/articles/ejhg2015269), at least on its own. Users want to triage and focus on the studies where OR that are significantly different from 1. This'd show that a SNP is associated with a disease.

**HOW are we going to solve the problem?**
Either add other statistics on a table format as a different column so that p-value, OR, etc are in individual columns for ease of downstream analyses with the downloaded file.

As an alternative we could provide an easy viz to convey the stats e.g. volcano plots (p value versus OR).

**Comment by andrewhercules** [comment]
Triage notes: 

- Have identified this as a suitable feature for a mini-release
- Will require creating a new column in the [Common Diseases table](https://www.targetvalidation.org/evidence/ENSG00000167207/EFO_0000384?view=sec:genetic_association) and exposing `data.unique_association_fields.odd_ratio` and `data.unique_association_fields.confidence_interval` if available
- Data already available from OT API - see [sample API response for NOD2 and Crohn's disease](https://api.opentargets.io/v3/platform/public/evidence/filter?size=1000&datasource=gwas_catalog&datasource=phewas_catalog&fields=unique_association_fields&fields=disease&fields=evidence&fields=variant&fields=target&fields=sourceID&fields=access_level&target=ENSG00000167207&disease=EFO_0000384&expandefo=true)

**Comment by andrewhercules** [comment]
Issue closed as it has already been raised in the webapp repo - see [issue #164](https://github.com/opentargets/webapp/issues/164)
