### ISSUE TITLE
Evidence Data type: Pathways and Systems Biology

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/roadmap#144]
**Description**
There are more and more papers that conduct comprehensive Systems Biology analyses to identify key driver genes for different diseases. They use different data types as input and apply different computation methods to find gene-disease associations. We want to include these sets of key driver genes and are planning to do so with a 'Pathways and Systems Biology' data type which will be based on the 'Affected Pathways' data type.

**HOW are we going to solve the problem?**  
1. In the first phase, Systems Biology papers that identify Key Driver Genes (KDGs) will be identified and curated. These will be used to define the evidence strings that need to be generated for this data type.
2. Then we will need to define how this new combined data type will be scored within the platform.
3. The new Systems Biology data source will have to be added to the pipeline.

**Describe technical design of the solution**
[Process for the addition of Systems Biology KDGs](https://docs.google.com/document/d/16YI0wy4mij3hMF_l-NKdCf-oedQFRgxbtlxF4xXFUPc/edit)
Link to the Data Specification Document will follow shortly.

**Comment by ElaineMcA** [comment]
Implemented as part of 18.12 release.  Follow-up activities will be tracked within specific issues in platform repository.
