### ISSUE TITLE
OTAR015 Evidence: Cancer Dependency Map

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/roadmap#145]
**Description**
The Open Targets Project OTAR015 CRISPR-cas9 Target ID performs a genome-wide loss-of-function CRISPR-cas9 screens across 500 genetically annotated human cancer cell lines to identify essential genes in the different cancer genomes. This data will be used to identify novel drug targets whose inhibition will be lethal to cancer cells with specific molecular alterations.

**HOW are we going to solve the problem?**  
1. Working with Fiona and Francesco to work out how the data will be integrated into the Open Targets Platform.

**Describe technical design of the solution**
 *Paste here google doc link or link to markdown file, if already written somewhere else*

**Comment by ElaineMcA** [comment]
Update received 23Oct2018:
Final data available for OT review by Dec 2018.
Publication timeline estimated - Jun2019.

**Comment by ElaineMcA** [comment]
Closing as progress tracked centrally via epic in platform repository. https://github.com/opentargets/platform/issues/163
