### ISSUE TITLE
login and user profiles

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#147]
@elipapa commented on [Tue Mar 28 2017](https://github.com/opentargets/biogen_instance/issues/30)

Allow identifiable login to the platform through Oauth (github, google, etc), which opens up the ability to save:
- gene sets / signatures
- "favorites"
- custom scoring
- etc.

**Comment by ElaineMcA** [comment]
Discussed with Ian and David prior to last strategy meeting - no plans to change access at this time.

Platform decisions documented centrally here.  Can re-open ticket if decision revisited.

https://docs.google.com/spreadsheets/d/1MDzuIMFgwM32ot-of-y9ewRh-tSPoS9LXhipTGxGRfQ/edit#gid=0
