### ISSUE TITLE
OTAR042 Target Prioritisation: Tractability

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/roadmap#149]
**Description**
The Open Targets Project OTAR042 is developing an *in silico* tractability assessment pipeline for small molecules and antibodies. The output of this project will be integrated into the Open Targets platform to allow for Target prioritisation.

**HOW are we going to solve the problem?**  
1. Chris from ChEMBL is working on the tractability project. The Open Targets core team will liaise with him to be kept up-to-date on progress.
2. Definition of where and how the tractability data will be included in the Open Targets Platform (backend and UX).

**Describe technical design of the solution**
 *Paste here google doc link or link to markdown file, if already written somewhere else*

### Progress Tracker

Iteration 1 of tractability data and feature release was executed in 18.10

18.12 Related open tickets for completion may be viewed here:
https://github.com/opentargets/platform/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3A+OTAR042

**Comment by ElaineMcA** [comment]
Tractability Part 1 released in 18.10.
Iteration 2 is scheduled for release as part of 18.12.

**Comment by ElaineMcA** [comment]
Implementation completed as part of 18.12 release.
