### ISSUE TITLE
fix duplications detected in evidence sources

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/roadmap#153]
@elipapa commented on [Wed May 16 2018](https://github.com/opentargets/data_pipeline/issues/279)

We currently use a set of fields in each evidence to create a hash/unique id and use that to write in ES. 
We found that we actually have a lot of collisions, most of which are false positives. 

We need to determine a list of specific fields _for each datatype_ that _uniquely_ determines the identity of an evidence and use that as the hash.

```
number of duplicated evidences= 1145976
number of uniq ids with duplication  566525
datasource        ids    duplications
eva_somatic                 1             2
progeny                11            22
reactome                21            42
eva               239           481
expression_atlas             40537         93629
europepmc            520482       1040964
gene2phenotype                13            26
phewas_catalog              4577          9396
gwas_catalog               533          1086
intogen               111           328
```

---

@ckongEbi commented on [Wed May 16 2018](https://github.com/opentargets/data_pipeline/issues/279#issuecomment-389555769)

The use of `unique_association_field` from JSONS to generate the unique evidence id in the platform backend can be problematic, as it might not fit the uniqueness requirements thus duplicates. 

![screen shot 2018-05-16 at 11 20 48](https://user-images.githubusercontent.com/6169985/40125787-aad4ec96-5923-11e8-81f8-4c9bd4fc4ae0.png)

**Comment by MichaelaEBI** [comment]
From @ckongEbi on July 17, 2018:

* EVA - 106 (Despite adding rs_id to unique_association_field, probably due to >1 clinvar traits mapping to same EFO terms, needs following up with EVA & @gkos-bio)
    Update 17JUL2018: Partially fixed in 18.08. Ontology mapping required @adam and Gautier.

* GWAS - 784 (Olga has flag this to GWAS curator for checking)
    Update 17JUL2018- Under investigation.

* ATLAS - 40459 (Suhaib planned to add probe_id to unique_association_field aim this will solve the issue)
    Update 17JUL2018: Fixed in 18.08.

* EUROPEPMC - 519807 (example sent to them but no feedback yet)
    Update 17JUL2018: Need to follow-up.

* PHEWAS - 117 (check with Eliseo)
    Update 17JUL2018: Need to follow-up.

**Comment by MichaelaEBI** [comment]
And another email later that same day:
Look for rows for counts > 1, which will be duplicates

* EVA: [1806_dup_eva_2.txt](https://github.com/opentargets/data_release/files/2201861/1806_dup_eva_2.txt)
* GWAS: [1806_dup_gwas_2.txt](https://github.com/opentargets/data_release/files/2201862/1806_dup_gwas_2.txt)
* PHEWAS: [18.06_phewas_2.txt](https://github.com/opentargets/data_release/files/2201882/18.06_phewas_2.txt)

EPMC & ATLAS:
https://drive.google.com/open?id=1levWwb8FgsmGm2bPsbS8ZZGOK1OAPSFv

**Comment by ElaineMcA** [comment]
https://github.com/opentargets/platform/issues/60

Closing this on roadmap as being tracked and addressed under platform repository data related issue.
