### ISSUE TITLE
Enhance existing search functionality

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/roadmap#159]
## Description
* [ ] **WHY - What is the problem this feature would answer?**  
Route users **as directly as possible** to the most relevant associations and evidence pages based upon the top hit results to access key data of interest across multiple entities.

* [ ] **HOW are we going to solve the problem?**  
Stage 1:
a) Confirm proposed behaviour for autocomplete feature based on usage stats
b) Review search function code to accommodate search via potential further entities e.g . drug, tissue, pathway.
c) Review subsequent requirements for refreshed search page design

Stage 2:
Potential to add chips to search field in order to build a query

Technical design under core team review to assess effort involved.

* [ ] **WHAT would this look like?**

**Comment by elipapa** [comment]
I would suggest:
1) split autocomplete, search and lookup in the API and data_pipeline
2) create a benchmark (eg. the average search ranking of a random 1000 genes)
3) optimize the search function to maximize the benchmark in 2. 

These steps are completely independent of allowing chips/tags in the search UI, but are necessary groundwork.

**Comment by ElaineMcA** [comment]
Other additional search considerations

(i) Consider requirement to search by PMID:
Users wants to see the genes and disease involved by a single paper, or all the evidence that is associated with the same piece of literature.

(ii) Search by pathway

Use case:
To get to which genes are involved in a given pathway - there is no way currently to search via UI on the pathway directly, only via API using the reactome id.

Currently within the platform, users can search a particular disease and filter via pathway facet.
Evidence page --> affected pathway section --> point to reactome.
Batch search requires two genes to search and obtain the information via this route.

**Comment by ElaineMcA** [comment]
Closing as any agreed actions will be addressed as appropriate within platform repository roadmap epics.
