### ISSUE TITLE
search by pathway

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#18]
this could be a shortcut to a batch-search of a list of genes. this approach has the added bonus of allowing definitions for gene sets and other entities composed of list of genes.

**Comment by ElaineMcA** [comment]
Use cases:
1. Which genes are involved in a given pathway - there is no way to search via UI on the pathway directly, only via API currently via reactome id.

Users can search a particular disease and filter via pathway facet.
Evidence page - affected pathway section - point to reactome.

Q: Any other pathway databases that are common and whether we are going to support?  Is there a future need for pathway as an entity?  Nice to have?

**Comment by ElaineMcA** [comment]
Addressed under pipeline refactoring issue
