### ISSUE TITLE
calculate and visualize "disease to disease" relationships based on shared T to D associations

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#22]

**Comment by andrewhercules** [comment]
Issue closed as feature has been integrated into Platform. On the [disease profile page](https://www.targetvalidation.org/disease/EFO_0000685), users can find similar diseases based on targets in common. See below for a screenshot:

![screen shot 2018-08-09 at 12 37 52](https://user-images.githubusercontent.com/7490258/43896544-17afd34a-9bd1-11e8-8f20-f5beb4cd75a8.png)
