### ISSUE TITLE
Infer new T<->D relationship from reactome pathways

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#25]

**Comment by andrewhercules** [comment]
Issue closed as Platform allows user to facet by Reactome pathways - see below:

![screen shot 2018-08-09 at 12 54 28](https://user-images.githubusercontent.com/7490258/43897356-9f154322-9bd3-11e8-8d7c-fdbe6ac1e669.png)

**Comment by elipapa** [comment]
this was not about faceting but about finding similar targets based on their membership in the same pathway with those targets included in the disease association page.

for eg. if we display target X as one of the top 25 targets involved in asthma, we should also offer a link to “browse targets in the same pathway”, whether they have links to asthma or not.


________________________________

**Comment by andrewhercules** [comment]
Ahh okay, makes sense - sorry about that. Will re-open for consideration.

**Comment by ElaineMcA** [comment]
Closing as covered as part of Networks project OTAR044.
