### ISSUE TITLE
drugbank

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#31]
http://www.drugbank.ca/	The DrugBank database is a unique bioinformatics and cheminformatics resource that combines detailed drug (i.e. chemical, pharmacological and pharmaceutical) data with comprehensive drug target (i.e. sequence, structure, and pathway) information.

**Comment by andrewhercules** [comment]
Triage notes:

- Have previously discussed this with @MichaelaEBI in relation to the `drug entity` project 
- As per the [DrugBank download page](https://www.drugbank.ca/releases/latest), the data is licensed under an [Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/legalcode) and cannot be used for commercial purposes
- Therefore, we cannot integrate it into our pipeline as some organisations may use our data for commercial purposes
- However, we can explore linking out to the DrugBank profile page on the [Platform drug profile page](https://www.targetvalidation.org/summary?drug=CHEMBL112)

**Comment by andrewhercules** [comment]
Issue closed as per triage notes above
