### ISSUE TITLE
matador

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#32]
http://matador.embl.de/	MATADOR is a resource for protein-chemical interactions. It differs from other resources such as DrugBank in its inclusion of as many direct and indirect interactions as we could find. In contrast, DrugBank usually contains only the main mode of interacton. The manually annotated list of direct (binding) and indirect interactions between proteins and chemicals was assembled by automated text-mining followed by manual curation.

**Comment by MichaelaEBI** [comment]
MATADOR is logged in the '[Data Source Backlog](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333)' on Google Drive. It was assessed by Ian, Elaine and myself in June 2018 and we noted: 'Out of date and commercial licence required.'
