### ISSUE TITLE
DGIdb

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#33]
WUSTL Drug Gene Interaction Database	Goal: To help you annotate your genes of interest with respect to known drug-gene interactions and potential druggability.

**Comment by MichaelaEBI** [comment]
DGIdb is logged in the '[Data Source Backlog](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333)' on Google Drive.
