### ISSUE TITLE
zinc15

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#34]
http://zinc15.docking.org/	

"respond to the question: ""are there compounds for these genes that i can go buy?""

a free database of commercially-available compounds for virtual screening.   ZINC contains over 35 million purchasable compounds in ready-to-dock, 3D formats. "

**Comment by MichaelaEBI** [comment]
ZINC15 is logged in the '[Data Source Backlog](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333)' on Google Drive.
