### ISSUE TITLE
add new prioritized cancer data sources

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#35]
CancerXGene	http://www.cancerrxgene.org	Genomics of Drug Sensitivity in Cancer
CancerXGene GDSC1000	http://www.cancerrxgene.org/gdsc1000/	A landscape of pharmacogenomic interaction in cancer: Resources and Results
CancerXGene GDSC1000 data summary	http://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources/Data_Summary.html	Data Summary

cBioportal	http://www.cbioportal.org	Access to large scale primary cancer genomics datasets from TCGA

CGAP: Cancer Genome Anatomy Project	http://cgap.nci.nih.gov	determine the gene expression profiles of normal, precancer, and cancer cells, leading eventually to improved detection, diagnosis, and treatment for the patient.

DoCM: Database of Curated Mutations	http://docm.genome.wustl.edu	highly curated database of known, disease-causing mutations that provides easily explorable variant lists with direct links to source citations for easy verification.

PMKB: Precision Medicine Knowledgebase	https://pmkb.weill.cornell.edu	PMKB is organized to provide information about clinical cancer variants and interpretations in a structured way, as well as allowing users to submit and edit existing entries for continued growth of the knowledgebase. All changes are reviewed by cancer pathologists.

canSAR	https://cansar.icr.ac.uk	an integrated knowledge-base that brings together multidisciplinary data across biology, chemistry, pharmacology, structural biology, cellular networks and clinical annotations, and applies machine learning approaches to provide drug-discovery useful predictions.

A CRISPR Dropout Screen Identifies Genetic Vulnerabilities and Therapeutic Targets in Acute Myeloid Leukemia	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5081405/	To identify additional therapeutic targets in AML, we optimize a genome-wide clustered regularly interspaced short palindromic repeats (CRISPR) screening platform and use it to identify genetic vulnerabilities in AML cells.

TCIA: The Cancer Imaging Archive	http://www.cancerimagingarchive.net	The image data is organized into purpose-built collections of subjects. The subjects typically have a cancer type and/or anatomical site (lung, brain, etc.) in common.

**Comment by MichaelaEBI** [comment]
All suggestions are logged in the '[Data Source Backlog](https://docs.google.com/spreadsheets/d/1QaaVOr3Oym1Hl0sJySrlMoBGUqf7ipfaXziQ9RiartU/edit#gid=1017254333)' on Google Drive and will be assessed shortly.
