### ISSUE TITLE
Show target names on Summary page of batch search

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/roadmap#39]
#  What problem does this feature solve?

[Participants in the first 3 sessions of the first iteration of batch search](https://docs.google.com/document/d/1ZDPWqSHhw4Kl_cOqBkTTaWNOG5VikrOLapeA2NCGz5w/edit?usp=sharing) (pull request #16) wanted to see names of targets associated with each TA/Disease and Pathway from the summary page. [The last participant specifically recommended](https://docs.google.com/document/d/1Hm83eVnMTzYT_q2-sggSaOSUzeYaYLnOTfKdEIiOAVM/edit?usp=sharing) showing the targets that are most strongly associated with each TA/Disease.

## Example use case

I have a list of targets associated with IBD. [In the summary page](https://drive.google.com/file/d/0B2ocPmrjJs1gcktUSTdBM0RWb2c/view?usp=sharing) I expect to see the names of the most strongly associated targets with each TA/Disease.

At the moment I need to click on the link for each TA/Disease and look at the filtered associations page for the names of the targets, then go back and click on the link for another TA/Disease, etc (This is an undesirable behaviour known as [pogo-sticking](https://www.nngroup.com/articles/pogo-sticking/)).

[x] Description complete

# What would it look like?

We need to consider the following questions when sketching solutions:
- How many targets to show for each TA/Disease?
- Will we rank them according to the association score? What will we use for targets in Pathways instead of the association score?

- Some participants were also interested in the "overlapping targets", especially for Pathways (but also for TAs/Diseases): How can we show these overlapping targets in the display?

- Would it make sense to consider a [heatmap like display in which diseases are grouped into TAs and targets into Pathways](https://drive.google.com/file/d/0B2ocPmrjJs1gQzVwdkpQd0c4Szg/view)?

**ACTION: MAKE SKETCHES BASED ON THE ABOVE**

[] Design complete

# How would we measure success of this feature?

- Analytics show no (or less) [pogo-sticking](https://www.nngroup.com/articles/pogo-sticking/).
- Positive user feedback for presence of target names (as per use case above)

[] Metrics complete

**Comment by andrewhercules** [comment]
Issue closed as batch search now shows the top 10 associated targets for each disease and/or therapeutic area. See below for an example:

![screen shot 2018-08-09 at 16 59 16](https://user-images.githubusercontent.com/7490258/43910762-9fd38b76-9bf5-11e8-8b43-f8f1407a8bda.png)
