### ISSUE TITLE
Help users find their targets in the Pathway diagram

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/roadmap#46]
# What problem does this feature solve?

While testing the first iteration of batch search (pull request #16) [participants could not find the targets from their list the Reactome Pathway diagram](https://docs.google.com/document/d/1ZDPWqSHhw4Kl_cOqBkTTaWNOG5VikrOLapeA2NCGz5w/edit#heading=h.2z7um3oa59q6):
![05-pathway-page-02-screencapture-beta-targetvalidation-org-summary-1478785401688](https://cloud.githubusercontent.com/assets/20280139/21990916/79e28bc8-dc08-11e6-8cce-d83e334e7435.png)

Some people described the diagram as confusing and hard to read. Nobody tried to interact with it.

At least one person from each group asked if we can get Pathways from sources other than Reactome (I think they meant both the diagram as well as other pathways that may not be in Reactome).

# What would it look like?

As a quick fix @emepyc suggested adding a purple border to the target name above the Pathway diagram (so that people can spot the target more easily in the Pathway) and turning the name into a highlighting switch (so that clicking e.g. on TYK highlights the reactions that include TYK2).

So it could look a bit more like this:
![05-pathway-page-02-screencapture-beta-targetvalidation-org-summary-1478785401688-border](https://cloud.githubusercontent.com/assets/20280139/21991339/1a6d6346-dc0a-11e6-8b67-48830dac83dd.png)

# How would we measure success of this feature?

- More positive user feedback for Pathways diagram
- More interaction with Pathways diagram
- More time on page (less bounce / exit rate)

**Comment by andrewhercules** [comment]
Issue closed as feature has been integrated into Platform as per specs above
