### ISSUE TITLE
facet/filter by drug attributes

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#51]
Filtering the drugs available on the open targets platform for a particular target to disease link, based on drug attributes:
- mode of action
- type/ protein class
- trial phase if  
would help screening/development Pharma scientist in identifying targets with higher chance of druggability. 

It would also help scientist evaluate existing compounds and opportunities for pipeline acquisition.

**Comment by ElaineMcA** [comment]
Addressed in part via tractability work ongoing.
