### ISSUE TITLE
QC before a release on beta - E2E user testing

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#63]
As the development team, it would be very helpful to automate checks for the overall consistency and quality of the final platform. 
- presence of UI element
- correct data
- lack of timeouts/ops problems. 

@deniseOme has begun collecting a list of those _manual_ checks that we usually perform
https://goo.gl/hON1pK

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #83](https://github.com/opentargets/platform/issues/83) via [**ZenHub**](https://www.zenhub.com/)
