### ISSUE TITLE
Redesign Drugs tables

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#76]
@nikiforosk commented on [Thu Jan 19 2017](https://github.com/opentargets/ux/issues/2)

These are the Drugs tables in 

**Target Profile > Drugs**:
![profile-egfr-drugs](https://cloud.githubusercontent.com/assets/20280139/21987972/7638cdda-dbfd-11e6-90ef-4cd366aa1218.png)

**Evidence page > Drugs**:
![evidence-efgr-adenocarcinoma-drugs](https://cloud.githubusercontent.com/assets/20280139/21987994/890767c8-dbfd-11e6-917c-7b9055f2f543.png)

There seems to be a lot of repetitive information, which is presumably generic i.e. **about the drug** itself.

Then there is information about the **clinical trial**, which is presumably different for each clinical trial.

Could we redesign this table so that we present:
1. General info about each drug (maybe as a drug card)
2. Info about each clinical trial (maybe as a table)

This could look similar to the section of TAs and Diseases that Miguel made for the Summary page of batch search:
![disease-table-tas-screen shot 2017-01-17 at 09 25 55](https://cloud.githubusercontent.com/assets/20280139/22109419/946c3f86-de4f-11e6-9c4b-8a68d79496d3.png)

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #7](https://github.com/opentargets/platform/issues/7) via [**ZenHub**](https://www.zenhub.com/)
