### ISSUE TITLE
filter expression evidence according to direction (up/down)

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/roadmap#81]
Several scientists from GSK have requested to be able to filter the expression evidence by direction.

E.g. in the [associations with asthma](https://www.targetvalidation.org/disease/EFO_0000270/associations?fcts=datatype:rna_expression) they'd like to know which targets are up-regulated and which ones are down-regulated (or both).

Searching for asthma in the Atlas produces results with an up/down regulation filter:
https://www.ebi.ac.uk/gxa/query?geneQuery=%5B%5D&organism=homo%20sapiens&conditionQuery=%5B%7B%22value%22%3A%22asthma%22%7D%5D&ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#differential

This could also apply to the RNA expression table on the evidence page (which can be sorted but not filtered by activity) e.g.: https://www.targetvalidation.org/evidence/ENSG00000073756/EFO_0003767?view=sec:rna_expression

**Comment by ElaineMcA** [comment]
Will be addressed as part of prioritisation view for tractability OTAR045.
