### ISSUE TITLE
How many studies are behind the associations table?

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/roadmap#82]
Example: 
More than 1000 targets are associated with asthma based on RNA expression information:
https://www.targetvalidation.org/disease/EFO_0000270/associations?fcts=datatype:rna_expression

But it turns out that many of these associations are reported in the same study. E.g. both 
https://www.targetvalidation.org/evidence/ENSG00000169245/EFO_0000270?view=sec:rna_expression
and 
https://www.targetvalidation.org/evidence/ENSG00000057657/EFO_0000270?view=sec:rna_expression
are part of the same study: 'human rhinovirus 16' vs 'vehicle' in 'asthma' in http://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-61141/ 

This is a bit easier to see if you search for "asthma" in the Atlas:
https://www.ebi.ac.uk/gxa/query?geneQuery=%5B%5D&organism=homo%20sapiens&conditionQuery=%5B%7B%22value%22%3A%22asthma%22%7D%5D&ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#differential

**Comment by ElaineMcA** [comment]
Closing this issue as it will be addressed by data team as part of this epic: https://github.com/opentargets/platform/issues/293
