### ISSUE TITLE
get drug information from papers using Pubmed

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#83]
@deniseOme commented on [Thu Mar 09 2017](https://github.com/opentargets/platform_issues_triage/issues/21)

At the omics integration course (March 2017 at EMBL-EBI), one student suggested mining literature for drug-disease information as another data source. Awaiting for more details from the user, specially examples.

**Comment by ElaineMcA** [comment]
Will be considered under drug profile page review.
