### ISSUE TITLE
I'd like to be able to download the associations for a gene or SNP

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#84]
@elipapa commented on [Tue Feb 21 2017](https://github.com/opentargets/platform_issues_triage/issues/5)

from _support email_
I'd like to be able to view in a table (and download) the associations for a gene (or SNP) all in one place

---

@elipapa commented on [Tue Feb 21 2017](https://github.com/opentargets/platform_issues_triage/issues/5#issuecomment-281212429)

We display the genomic context of a gene and its SNPs with associations upon clicking the lollipops. Could a table be provided? GWAS catalog provides this. Shall we replicate it? Shall we link out to them (https://www.ebi.ac.uk/gwas/search?query=clec16a). Need to be careful: we may want to change the focus of people: instead of looking at every single SNP to taking the whole genomic region at once.

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues_triage/issues/5#issuecomment-296718974)

this could fit either in the target profile or the associations page, but is basically a wrapper around the existing API functionality

**Comment by andrewhercules** [comment]
Triage notes:

- Issue will be resolved with the introduction of the Genetics Portal as users will be able to download a table of associated genes and associated SNPs based on the G2V pipeline

**Comment by andrewhercules** [comment]
Issue closed as per triage notes above
