### ISSUE TITLE
drug scores to reflect status of clinical trials AND show activity/withdrawn in evidence

### ISSUE THREAD

**Issue by elipapa** [opentargets/roadmap#99]
## Description
* [x] **WHY - What is the problem this feature would answer?**  

Targets which have failed clinical trials should be severely penalized in the overall ranking. Currently we only consider biological evidence, but we don't leverage the real world evidence which often shows the lack of efficacy of some of the targets associated with disease.

* [ ] **HOW are we going to solve the problem?**  

Currently CHEMBL is interested in providing (and maintaining) a solution for this.

* [ ] **WHAT would this look like?**
> *Screenshots and mock-ups are great*
 

### Get to a prototype at branch.targetvalidation.org:
> Write code + **tests** + docs. Isolate the work in feature branches.  
> Use as many PRs as you need.  
> Write tests in the same or different PRs, as is convenient for you.  
> As each PR is merged, add a comment to this issue referencing the PRs.  

- [ ] Feature tag *Code should have a feature tag to be disabled by default.*
- [ ] Minimal functional testing
- [ ] Minimal docs
- [ ] if on webapp, test a deployment on netlify
       
### Push to staging
- [ ] merged code and pushed to staging.targetvalidation.org
  **PULL request should be reviewed by 1-2 people at least**
- [ ] at least 1 week internal testing?
- [ ] received some feedback/input from users (eg. pharma scientist)

### Released
- [ ] in the release notes?
- [ ] documentation updated?		
- [ ] blog post?
- [ ] users that requested it originally informed?

## Make sure you can measure impact
> As dev team we want to know if a new feature are succesful.
> To do that we need to define metrics to assess the impact of each new feature we introduce to the platform
- [ ] metric identified 
- [ ] identify the one metric that matters (OMTM)

**Comment by andrewhercules** [comment]
Just to track users that have gotten in touch about this issue, earlier today we received the following email from Iain Wallace at Merck:

The feedback aspect would also be useful on the main site to flag problematic associations. For example ABL1 is linked to heart disease via a gleevec due to safety studies rather than mechanism of action based trials.
https://www.targetvalidation.org/evidence/ENSG00000097007/EFO_0000319?view=sec:known_drug
